export const categoryColors: Record<string, { color: string; bg: string }> = {
  jar:                    { color: "#7C3AED", bg: "#F3F0FF" },
  "jar-gold":             { color: "#D97706", bg: "#FEF9EC" },
  "jar-silver":           { color: "#64748B", bg: "#F1F5F9" },
  kyc:                    { color: "#059669", bg: "#ECFDF5" },
  "upi-id":               { color: "#2563EB", bg: "#EFF6FF" },
  "payments-savings":     { color: "#7C3AED", bg: "#F3F0FF" },
  "autopay-subscription": { color: "#0891B2", bg: "#ECFEFF" },
  withdrawal:             { color: "#059669", bg: "#ECFDF5" },
  "refer-earn":           { color: "#DC2626", bg: "#FEF2F2" },
  rewards:                { color: "#D97706", bg: "#FEF9EC" },
  profile:                { color: "#4F46E5", bg: "#EEF2FF" },
  nominee:                { color: "#7C3AED", bg: "#F3F0FF" },
  loans:                  { color: "#64748B", bg: "#F1F5F9" },
  "jar-pay":              { color: "#2563EB", bg: "#EFF6FF" },
  nek:                    { color: "#DB2777", bg: "#FDF2F8" },
  "report-fraud":         { color: "#DC2626", bg: "#FEF2F2" },
  "nek-delivery":         { color: "#EA580C", bg: "#FFF7ED" },
  "upi-help":             { color: "#0284C7", bg: "#F0F9FF" },
};
