export const categoryColors: Record<string, { color: string; bg: string }> = {
  jar:                    { color: "#7C3AED", bg: "#F3F0FF" },
  "jar-gold":             { color: "#B45309", bg: "#FEF9EC" },
  "jar-silver":           { color: "#475569", bg: "#F1F5F9" },
  kyc:                    { color: "#059669", bg: "#ECFDF5" },
  "upi-id":               { color: "#2563EB", bg: "#DBEAFE" },
  "payments-savings":     { color: "#16A34A", bg: "#DCFCE7" },
  "autopay-subscription": { color: "#DB2777", bg: "#FCE7F3" },
  withdrawal:             { color: "#DC2626", bg: "#FEE2E2" },
  "refer-earn":           { color: "#7C3AED", bg: "#EDE9FE" },
  rewards:                { color: "#D97706", bg: "#FFFBEB" },
  profile:                { color: "#4F46E5", bg: "#EEF2FF" },
  nominee:                { color: "#7E22CE", bg: "#FAF5FF" },
  loans:                  { color: "#64748B", bg: "#F8FAFC" },
  "jar-pay":              { color: "#1D4ED8", bg: "#EFF6FF" },
  nek:                    { color: "#DB2777", bg: "#FDF2F8" },
  "report-fraud":         { color: "#B91C1C", bg: "#FEF2F2" },
  "nek-delivery":         { color: "#EA580C", bg: "#FFF7ED" },
  "upi-help":             { color: "#0284C7", bg: "#F0F9FF" },
};
